#include <string.h>
#include <stdio.h>
#include <stdbool.h>

union val{
	int int_val;
	bool bool_val;
	char char_val;
	float float_val;
};

union val MM[10000];
union val R[10000];
union val R2[10000];

int main(){
FILE *outfile; outfile = fopen("output.txt","w");

FILE *infile; infile = fopen("input.txt","r");

R[0].char_val='l';
	R[1].char_val='o';
	R[2].char_val='l';
	R[3].char_val=' ';
	R[4].char_val=' ';
	R[5].char_val=' ';
	R[6].char_val=' ';
	R[7].char_val=' ';
	R[8].char_val=' ';
	R[9].char_val=' ';
	R[10].char_val=' ';
	R[11].char_val=' ';
	R[12].char_val=' ';
	R[13].char_val=' ';
	R[14].char_val=' ';
	R[15].char_val=' ';
	R[16].char_val=' ';
	R[17].char_val=' ';
	R[18].char_val=' ';
	R[19].char_val=' ';
	R[20].char_val=' ';
	R[21].char_val=' ';
	R[22].char_val=' ';
	R[23].char_val=' ';
	R[24].char_val=' ';
	R[25].char_val=' ';
	R[26].char_val=' ';
	R[27].char_val=' ';
	R[28].char_val=' ';
	R[29].char_val=' ';
	R[30].char_val=' ';
	R[31].char_val=' ';
	R[32].char_val=' ';
	R[33].char_val=' ';
	R[34].char_val=' ';
	R[35].char_val=' ';
	R[36].char_val=' ';
	R[37].char_val=' ';
	R[38].char_val=' ';
	R[39].char_val=' ';
	R[40].char_val=' ';
	R[41].char_val=' ';
	R[42].char_val=' ';
	R[43].char_val=' ';
	R[44].char_val=' ';
	R[45].char_val=' ';
	R[46].char_val=' ';
	R[47].char_val=' ';
	R[48].char_val=' ';
	R[49].char_val=' ';
	
	MM[0].char_val=R[0].char_val;
	MM[1].char_val=R[1].char_val;
	MM[2].char_val=R[2].char_val;
	MM[3].char_val=R[3].char_val;
	MM[4].char_val=R[4].char_val;
	MM[5].char_val=R[5].char_val;
	MM[6].char_val=R[6].char_val;
	MM[7].char_val=R[7].char_val;
	MM[8].char_val=R[8].char_val;
	MM[9].char_val=R[9].char_val;
	MM[10].char_val=R[10].char_val;
	MM[11].char_val=R[11].char_val;
	MM[12].char_val=R[12].char_val;
	MM[13].char_val=R[13].char_val;
	MM[14].char_val=R[14].char_val;
	MM[15].char_val=R[15].char_val;
	MM[16].char_val=R[16].char_val;
	MM[17].char_val=R[17].char_val;
	MM[18].char_val=R[18].char_val;
	MM[19].char_val=R[19].char_val;
	MM[20].char_val=R[20].char_val;
	MM[21].char_val=R[21].char_val;
	MM[22].char_val=R[22].char_val;
	MM[23].char_val=R[23].char_val;
	MM[24].char_val=R[24].char_val;
	MM[25].char_val=R[25].char_val;
	MM[26].char_val=R[26].char_val;
	MM[27].char_val=R[27].char_val;
	MM[28].char_val=R[28].char_val;
	MM[29].char_val=R[29].char_val;
	MM[30].char_val=R[30].char_val;
	MM[31].char_val=R[31].char_val;
	MM[32].char_val=R[32].char_val;
	MM[33].char_val=R[33].char_val;
	MM[34].char_val=R[34].char_val;
	MM[35].char_val=R[35].char_val;
	MM[36].char_val=R[36].char_val;
	MM[37].char_val=R[37].char_val;
	MM[38].char_val=R[38].char_val;
	MM[39].char_val=R[39].char_val;
	MM[40].char_val=R[40].char_val;
	MM[41].char_val=R[41].char_val;
	MM[42].char_val=R[42].char_val;
	MM[43].char_val=R[43].char_val;
	MM[44].char_val=R[44].char_val;
	MM[45].char_val=R[45].char_val;
	MM[46].char_val=R[46].char_val;
	MM[47].char_val=R[47].char_val;
	MM[48].char_val=R[48].char_val;
	MM[49].char_val=R[49].char_val;
fprintf(outfile, "%c",MM[0].char_val);
fprintf(outfile, "%c",MM[1].char_val);
fprintf(outfile, "%c",MM[2].char_val);
fprintf(outfile, "%c",MM[3].char_val);
fprintf(outfile, "%c",MM[4].char_val);
fprintf(outfile, "%c",MM[5].char_val);
fprintf(outfile, "%c",MM[6].char_val);
fprintf(outfile, "%c",MM[7].char_val);
fprintf(outfile, "%c",MM[8].char_val);
fprintf(outfile, "%c",MM[9].char_val);
fprintf(outfile, "%c",MM[10].char_val);
fprintf(outfile, "%c",MM[11].char_val);
fprintf(outfile, "%c",MM[12].char_val);
fprintf(outfile, "%c",MM[13].char_val);
fprintf(outfile, "%c",MM[14].char_val);
fprintf(outfile, "%c",MM[15].char_val);
fprintf(outfile, "%c",MM[16].char_val);
fprintf(outfile, "%c",MM[17].char_val);
fprintf(outfile, "%c",MM[18].char_val);
fprintf(outfile, "%c",MM[19].char_val);
fprintf(outfile, "%c",MM[20].char_val);
fprintf(outfile, "%c",MM[21].char_val);
fprintf(outfile, "%c",MM[22].char_val);
fprintf(outfile, "%c",MM[23].char_val);
fprintf(outfile, "%c",MM[24].char_val);
fprintf(outfile, "%c",MM[25].char_val);
fprintf(outfile, "%c",MM[26].char_val);
fprintf(outfile, "%c",MM[27].char_val);
fprintf(outfile, "%c",MM[28].char_val);
fprintf(outfile, "%c",MM[29].char_val);
fprintf(outfile, "%c",MM[30].char_val);
fprintf(outfile, "%c",MM[31].char_val);
fprintf(outfile, "%c",MM[32].char_val);
fprintf(outfile, "%c",MM[33].char_val);
fprintf(outfile, "%c",MM[34].char_val);
fprintf(outfile, "%c",MM[35].char_val);
fprintf(outfile, "%c",MM[36].char_val);
fprintf(outfile, "%c",MM[37].char_val);
fprintf(outfile, "%c",MM[38].char_val);
fprintf(outfile, "%c",MM[39].char_val);
fprintf(outfile, "%c",MM[40].char_val);
fprintf(outfile, "%c",MM[41].char_val);
fprintf(outfile, "%c",MM[42].char_val);
fprintf(outfile, "%c",MM[43].char_val);
fprintf(outfile, "%c",MM[44].char_val);
fprintf(outfile, "%c",MM[45].char_val);
fprintf(outfile, "%c",MM[46].char_val);
fprintf(outfile, "%c",MM[47].char_val);
fprintf(outfile, "%c",MM[48].char_val);
fprintf(outfile, "%c",MM[49].char_val);
fscanf(infile, "%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c",&MM[0].char_val,&MM[1].char_val,&MM[2].char_val,&MM[3].char_val,&MM[4].char_val,&MM[5].char_val,&MM[6].char_val,&MM[7].char_val,&MM[8].char_val,&MM[9].char_val,&MM[10].char_val,&MM[11].char_val,&MM[12].char_val,&MM[13].char_val,&MM[14].char_val,&MM[15].char_val,&MM[16].char_val,&MM[17].char_val,&MM[18].char_val,&MM[19].char_val,&MM[20].char_val,&MM[21].char_val,&MM[22].char_val,&MM[23].char_val,&MM[24].char_val,&MM[25].char_val,&MM[26].char_val,&MM[27].char_val,&MM[28].char_val,&MM[29].char_val,&MM[30].char_val,&MM[31].char_val,&MM[32].char_val,&MM[33].char_val,&MM[34].char_val,&MM[35].char_val,&MM[36].char_val,&MM[37].char_val,&MM[38].char_val,&MM[39].char_val,&MM[40].char_val,&MM[41].char_val,&MM[42].char_val,&MM[43].char_val,&MM[44].char_val,&MM[45].char_val,&MM[46].char_val,&MM[47].char_val,&MM[48].char_val,&MM[49].char_val);
fprintf(outfile, "%c",MM[0].char_val);
fprintf(outfile, "%c",MM[1].char_val);
fprintf(outfile, "%c",MM[2].char_val);
fprintf(outfile, "%c",MM[3].char_val);
fprintf(outfile, "%c",MM[4].char_val);
fprintf(outfile, "%c",MM[5].char_val);
fprintf(outfile, "%c",MM[6].char_val);
fprintf(outfile, "%c",MM[7].char_val);
fprintf(outfile, "%c",MM[8].char_val);
fprintf(outfile, "%c",MM[9].char_val);
fprintf(outfile, "%c",MM[10].char_val);
fprintf(outfile, "%c",MM[11].char_val);
fprintf(outfile, "%c",MM[12].char_val);
fprintf(outfile, "%c",MM[13].char_val);
fprintf(outfile, "%c",MM[14].char_val);
fprintf(outfile, "%c",MM[15].char_val);
fprintf(outfile, "%c",MM[16].char_val);
fprintf(outfile, "%c",MM[17].char_val);
fprintf(outfile, "%c",MM[18].char_val);
fprintf(outfile, "%c",MM[19].char_val);
fprintf(outfile, "%c",MM[20].char_val);
fprintf(outfile, "%c",MM[21].char_val);
fprintf(outfile, "%c",MM[22].char_val);
fprintf(outfile, "%c",MM[23].char_val);
fprintf(outfile, "%c",MM[24].char_val);
fprintf(outfile, "%c",MM[25].char_val);
fprintf(outfile, "%c",MM[26].char_val);
fprintf(outfile, "%c",MM[27].char_val);
fprintf(outfile, "%c",MM[28].char_val);
fprintf(outfile, "%c",MM[29].char_val);
fprintf(outfile, "%c",MM[30].char_val);
fprintf(outfile, "%c",MM[31].char_val);
fprintf(outfile, "%c",MM[32].char_val);
fprintf(outfile, "%c",MM[33].char_val);
fprintf(outfile, "%c",MM[34].char_val);
fprintf(outfile, "%c",MM[35].char_val);
fprintf(outfile, "%c",MM[36].char_val);
fprintf(outfile, "%c",MM[37].char_val);
fprintf(outfile, "%c",MM[38].char_val);
fprintf(outfile, "%c",MM[39].char_val);
fprintf(outfile, "%c",MM[40].char_val);
fprintf(outfile, "%c",MM[41].char_val);
fprintf(outfile, "%c",MM[42].char_val);
fprintf(outfile, "%c",MM[43].char_val);
fprintf(outfile, "%c",MM[44].char_val);
fprintf(outfile, "%c",MM[45].char_val);
fprintf(outfile, "%c",MM[46].char_val);
fprintf(outfile, "%c",MM[47].char_val);
fprintf(outfile, "%c",MM[48].char_val);
fprintf(outfile, "%c",MM[49].char_val);

fclose(outfile);
fclose(infile);
}